site_name: mycookiecutter
site_description: Its all about a Weissman score > 5.0
repo_url: https://github.com/krystianfranus/my-cookiecutter
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/krystianfranus">krystianfranus</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
